### ISSUE TITLE
Nerve shutdown doesn't de-register

### ISSUE THREAD

**Issue by jbkielis** [themecloud/Dockstack#1]
It doesn't appear that a Nerve shutdown removes the service's entry from Zookeeper, so Synapse thinks it's still alive.  I'm hoping its just my setup.  Can you confirm that works?

Thanks!

**Comment by asiragusa** [comment]
Even if the service's entry is in Zookeeper, HAProxy detects that the service is down, so it's not a real issue.

yw

**Comment by jbkielis** [comment]
Thanks. Unfortunately it is actually an issue because of cases where I want
to gracefully take down a node for maintenance. Rather than disabling at
each synapse, I want to disable it on the nerve side. And I can't just stop
the node itself because it will still be handling requests while I'm taking
it down.

Can you confirm that it works for you?

Thanks again.

**Comment by asiragusa** [comment]
Take a look at HAProxy's stats page, there you can see if it restarts once you kill the nerve node. In my case it happens after just few seconds.

**Comment by jbkielis** [comment]
Ok, unfortunately not working for me. Haproxy still thinks the node is
alive (because it technically is) even though nerve has been shutdown.

**Comment by asiragusa** [comment]
Can you give me more details about your config please?

**Comment by jbkielis** [comment]
Sure Allessandro,

I'm running two VMs.  I've provided full setup commands below.  To
reproduce the issue, shutdown Nerve on VM2.  VM1 still thinks the http
service is live.  I believe Nerve should instead remove the entry from
Zookeeper upon shutdown so that VM1 doesn't see it anymore.

_VM1:_
- dockerized Zookeeper
- dockerized Synapse

_Setup commands:_
HOST_IP=$(hostname --all-ip-addresses | awk '{print $1}')
docker run -d -p 2181:2181 -p 2888:2888 -p 3888:3888 --name zookeeper
jplock/zookeeper
docker run -d --name synapse -p 8080:8080 -p 80:80 tcio/dockstack-synapse
-d zk://$HOST_IP:2181/nerve -s whoami_80:http:/whoami

_VM2:_
- dockerized http service
- dockerized Nerve

_Setup commands:_
docker run -d -p 80:80 --name whoami -t jbkielis/whoami
HOST_IP=$(hostname --all-ip-addresses | awk '{print $1}')
ZK_IP=10.0.0.5
docker run -d --name nerve -v /usr/bin/docker:/usr/bin/docker:ro -v
/lib64/libdevmapper.so.1.02:/lib/libdevmapper.so.1.02:ro -v
/var/run/docker.sock:/var/run/docker.sock -e SERVICE_HOST=$HOST_IP
tcio/dockstack-nerve -d zk://$ZK_IP:2181/nerve -s
whoami:http:whoami:80:/whoami

**Comment by jbkielis** [comment]
It appears there's some issue when Nerve shuts down in that it can't delete
the Zookeeper key.  Here's the log from Zookeeper during Nerve shutdown:

[image: Inline image 1]

**Comment by asiragusa** [comment]
Can you please copy paste the logs in pastebin? The I can't see the image.

**Comment by asiragusa** [comment]
Can you try the setup with two http/nerve vms? I think that the last entry is not removed to avoid an outage in case nerve fails. With 2+ http/nerve vms it should work as you expect.

**Comment by ymsaout** [comment]
@ jbkielis

I'm going to test it with 1 and 2 hosts. Are you able to curl Zookeeper with your jplock/zookeeper container ?

**Comment by jbkielis** [comment]
Alessandro,

Zookeeper log is here:
https://drive.google.com/file/d/0B15N2OKVN5McZWNxeUtSZjB2RWM/view?usp=sharing

Thanks.

**Comment by asiragusa** [comment]
The logs only say that the client has unexpectedly terminated the connection. 

I tested killing all the nerve nodes in a cluster and the last one stays alive in my case too. 

It's not a problem imho, because I think that at least you want one node to stay alive, as long as you don't want to bring down the whole service. 

I'm using this config since longtime and I never had an issue.

The only improvement for this setup may be done on the haproxy's restart, as some packets may be lost in the meantime. Here it's explained well: http://engineeringblog.yelp.com/2015/04/true-zero-downtime-haproxy-reloads.html

If you want to do a PR you are welcome :)
